### ISSUE TITLE
Why two year old freertos?

### ISSUE THREAD

**Issue by ObligedTester** [Evlers/pico-freertos#1]
Hello!

Thank you for the work on this repository.

Just curious, it looks like the freertos used in the submodule is from a version released over 2 years ago, is there any reason for this?

**Comment by Evlers** [comment]
Because this submodule uses the SMP branch of freertos

**Comment by ObligedTester** [comment]
Oh I see. So the SMP Branch has not been updated in 2 years?

**Comment by Evlers** [comment]
You can go to the [freertos](https://github.com/FreeRTOS/FreeRTOS-Kernel) repository，have a commit recently.
This commit doesn't matter, it just updates the readme file.
